language: node_js
node_js:
  - "8.9"
  - "9"
  - "10"
matrix:
  include:
    - node_js: "10"
      env: "NVM_NODEJS_ORG_MIRROR=https://nodejs.org/download/nightly"
  allow_failures:
    - env: "NVM_NODEJS_ORG_MIRROR=https://nodejs.org/download/nightly"
sudo: false
